In [2]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor

In [3]:
path_train = 'data/base_train.csv'
path_test = 'data/base_test.csv'
df_train = pd.read_csv(path_train) #get train set as a dataframe
df_test = pd.read_csv(path_test) #get test set as a dataframe
df_train #show dataframe training-set

kOH    0    1    2    3    4    5    6    7    8  ...  1014  \
0    2.690000e+08  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   
1    1.290000e+08  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   
2    3.240000e+08  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   
3    3.800000e+08  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   
4    1.100000e+09  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   
..            ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   ...   
495  7.700000e+09  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   
496  1.700000e+09  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   
497  6.100000e+09  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   
498  4.500000e+09  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   
499  1.800000e+10  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   

     1015  1016  1017  1018  1019  1020  1021  1022  1023  
0     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
1     0.0   0.0   0.0   0.0   0.0   0.0   1.0   0.0   0.0  
2     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
3     0.0   0.0   0.0   0.0   0.0   0.0   1.0   0.0   0.0  
4     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
..    ...   ...   ...   ...   ...   ...   ...   ...   ...  
495   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
496   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
497   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
498   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
499   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  

[500 rows x 1025 columns]

In [4]:
df_test #show dataframe test-set

kOH    0    1    2    3    4    5    6    7    8  ...  1014  \
0    1.500000e+09  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   
1    7.000000e+09  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  ...   0.0   
2    3.500000e+09  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   
3    4.000000e+09  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   
4    6.800000e+07  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   
..            ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   ...   
131  3.100000e+09  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  ...   0.0   
132  2.500000e+09  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   
133  1.300000e+10  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   
134  1.300000e+10  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   
135  1.200000e+10  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   

     1015  1016  1017  1018  1019  1020  1021  1022  1023  
0     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
1     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
2     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
3     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
4     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
..    ...   ...   ...   ...   ...   ...   ...   ...   ...  
131   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
132   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
133   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
134   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
135   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  

[136 rows x 1025 columns]

In [5]:
#separate xi and y features as a matrix/array
xi_train = df_train.iloc[:, 1:].values
xi_test = df_test.iloc[:, 1:].values
y_train = df_train.iloc[:, 0].values
y_test = df_test.iloc[:, 0].values
xi_train #show xi_train matrix

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [6]:
y_test #show y_test array

array([1.50e+09, 7.00e+09, 3.50e+09, 4.00e+09, 6.80e+07, 7.80e+08,
       2.50e+08, 4.70e+08, 7.00e+09, 7.00e+09, 5.40e+09, 7.70e+09,
       8.50e+09, 1.30e+10, 1.20e+09, 1.50e+09, 5.80e+09, 1.10e+10,
       3.90e+09, 5.70e+09, 5.30e+09, 9.70e+09, 8.40e+09, 1.50e+10,
       5.90e+09, 9.50e+09, 1.10e+10, 1.00e+10, 2.10e+10, 1.00e+10,
       6.30e+09, 1.10e+10, 1.20e+10, 1.20e+10, 7.80e+08, 3.50e+09,
       1.90e+10, 7.50e+09, 1.00e+10, 1.40e+10, 1.30e+09, 3.30e+09,
       7.00e+09, 1.00e+10, 8.30e+09, 3.00e+10, 8.00e+09, 1.00e+10,
       5.20e+09, 7.00e+09, 2.00e+10, 2.00e+10, 6.20e+09, 1.40e+09,
       7.20e+09, 7.00e+09, 7.50e+09, 7.20e+09, 8.00e+09, 7.10e+09,
       7.00e+09, 7.00e+09, 1.20e+10, 1.00e+10, 8.60e+09, 2.10e+10,
       3.10e+09, 4.10e+09, 3.70e+09, 3.90e+09, 1.50e+09, 2.00e+09,
       1.10e+09, 9.60e+09, 9.50e+09, 2.50e+09, 2.40e+09, 8.40e+09,
       5.00e+09, 2.40e+09, 1.10e+09, 1.80e+09, 3.10e+09, 7.50e+08,
       6.50e+09, 5.40e+09, 1.10e+10, 5.30e+09, 6.20e+09, 1.60e

In [7]:
#traning a regression model (sklearn)
rlr = RandomForestRegressor(n_estimators=150)
rlr.fit(xi_train, y_train)

RandomForestRegressor(n_estimators=150)

## Work with pyADA

In [8]:
from pyADA import Smetrics, Similarity, ApplicabilityDomain

In [9]:
# Internal documentation
help(Similarity)

Help on class Similarity in module pyADA.pyADA:

class Similarity(builtins.object)
 |  All similarity calculations have a range of [0, 1]
 |  
 |  Methods defined here:
 |  
 |  __init__(self)
 |      Initialize self.  See help(type(self)) for accurate signature.
 |  
 |  arithmetic_similarity(self, vetor1, vetor2)
 |      Dice similarity - Calculates the ratio of the bits in common to the
 |      arithmetic mean of the number of “on” bits in the
 |      two fingerprints.
 |  
 |  euclidian_similarity(self, vetor1, vetor2)
 |      Similarity based on Euclidean distance of two vectors.
 |  
 |  geometric_similarity(self, vetor1, vetor2)
 |      Cosine Similarity - Calculates the ratio of the bits in common to
 |      the geometric mean of the number of “on” bits
 |      in the two fingerprints.
 |  
 |  manhattan_similarity(self, vetor1, vetor2)
 |      Similarity based on Manhattan distance of two vectors.
 |  
 |  tanimoto_similarity(self, vetor1, vetor2)
 |      Structural similarity

In [10]:
help(ApplicabilityDomain)

Help on class ApplicabilityDomain in module pyADA.pyADA:

class ApplicabilityDomain(builtins.object)
 |  ApplicabilityDomain(verbose=False)
 |  
 |  Methods defined here:
 |  
 |  __init__(self, verbose=False)
 |      Initialize self.  See help(type(self)) for accurate signature.
 |  
 |  analyze_similarity(self, base_test, base_train, similarity_metric='tanimoto', alpha=1, beta=1)
 |      Analysis of the similarity between molecular fingerprints
 |      using different metrics. A table (dataframe pandas) will be
 |      generated with the coefficients: Average, median, std,
 |      maximum similarity and minimum similarity, for all compounds
 |      in the test database in relation to the training database.
 |      The alpha and beta parameters are only for 'tversky' metric.
 |      
 |      Arguments
 |      ---------------------
 |      base_test
 |          Must be a numpy matrix containing only the fingerprints of all molecules in the test database.
 |          
 |              >>

In [11]:
AD = ApplicabilityDomain(verbose=True)

In [12]:
#Analysis of similarities between the structures of the test-set and training-set 
sims = AD.analyze_similarity(base_test=xi_test, base_train=xi_train,
                             similarity_metric='tanimoto')
sims

100%|██████████| 136/136 [00:01<00:00, 68.00it/s]


Mean    Median       Std       Max  Min
Sample_test_0    0.033473  0.020833  0.052884  0.625000  0.0
Sample_test_1    0.061249  0.038711  0.078559  0.772727  0.0
Sample_test_2    0.087280  0.058140  0.089640  0.642857  0.0
Sample_test_3    0.091395  0.062500  0.089597  0.666667  0.0
Sample_test_4    0.107003  0.066667  0.115979  0.600000  0.0
...                   ...       ...       ...       ...  ...
Sample_test_131  0.090089  0.055556  0.082320  0.595745  0.0
Sample_test_132  0.120658  0.069205  0.133551  0.884615  0.0
Sample_test_133  0.116800  0.055556  0.151737  0.923077  0.0
Sample_test_134  0.116800  0.055556  0.151737  0.923077  0.0
Sample_test_135  0.061264  0.037269  0.061960  0.354167  0.0

[136 rows x 5 columns]

In [14]:
#All similarities values
AD.similarities_table_

Sample_test_0  Sample_test_1  Sample_test_2  Sample_test_3  \
0         0.058824       0.076923       0.142857       0.157895   
1         0.000000       0.043478       0.052632       0.058824   
2         0.000000       0.068966       0.038462       0.041667   
3         0.000000       0.086957       0.050000       0.055556   
4         0.000000       0.020408       0.045455       0.047619   
..             ...            ...            ...            ...   
495       0.000000       0.136364       0.050000       0.055556   
496       0.050000       0.107143       0.125000       0.136364   
497       0.000000       0.142857       0.052632       0.058824   
498       0.000000       0.150000       0.055556       0.062500   
499       0.000000       0.304348       0.040000       0.043478   

     Sample_test_4  Sample_test_5  Sample_test_6  Sample_test_7  \
0         0.250000       0.235294       0.285714       0.235294   
1         0.100000       0.062500       0.076923       0.062500   
2         0.058824       0.090909       0.105263       0.090909   
3         0.090909       0.125000       0.153846       0.125000   
4         0.000000       0.023810       0.025641       0.023810   
..             ...            ...            ...            ...   
495       0.090909       0.200000       0.153846       0.125000   
496       0.200000       0.411765       0.312500       0.263158   
497       0.100000       0.214286       0.166667       0.133333   
498       0.111111       0.230769       0.181818       0.142857   
499       0.062500       0.045455       0.052632       0.045455   

     Sample_test_8  Sample_test_9  ...  Sample_test_126  Sample_test_127  \
0         0.153846       0.083333  ...         0.142857         0.133333   
1         0.100000       0.125000  ...         0.090909         0.083333   
2         0.125000       0.066667  ...         0.117647         0.111111   
3         0.200000       0.111111  ...         0.181818         0.166667   
4         0.000000       0.000000  ...         0.000000         0.000000   
..             ...            ...  ...              ...              ...   
495       0.200000       0.111111  ...         0.625000         0.750000   
496       0.125000       0.066667  ...         0.357143         0.428571   
497       0.222222       0.125000  ...         0.714286         0.857143   
498       0.250000       0.142857  ...         0.833333         0.500000   
499       0.062500       0.071429  ...         0.058824         0.055556   

     Sample_test_128  Sample_test_129  Sample_test_130  Sample_test_131  \
0           0.000000         0.000000         0.028571         0.050000   
1           0.000000         0.000000         0.032258         0.027027   
2           0.000000         0.000000         0.026316         0.022727   
3           0.000000         0.000000         0.031250         0.026316   
4           0.272727         0.115385         0.260870         0.142857   
..               ...              ...              ...              ...   
495         0.000000         0.000000         0.031250         0.026316   
496         0.000000         0.000000         0.026316         0.046512   
497         0.000000         0.000000         0.032258         0.027027   
498         0.000000         0.000000         0.033333         0.027778   
499         0.000000         0.055556         0.027027         0.023256   

     Sample_test_132  Sample_test_133  Sample_test_134  Sample_test_135  
0           0.090909         0.045455         0.045455         0.028169  
1           0.103448         0.000000         0.000000         0.014706  
2           0.083333         0.000000         0.000000         0.027027  
3           0.100000         0.000000         0.000000         0.029412  
4           0.115385         0.153846         0.153846         0.144578  
..               ...              ...              ...              ...  
495         0.031250         0.000000         0.000000         

In [16]:
#scan of similarities to found threshold
result = AD.fit(model_sklearn=rlr, base_test=xi_test, base_train=xi_train,
                y_true=y_test, threshold_step=(0, 1, 0.1), threshold_reference='max',
                similarity_metric='tanimoto', metric_error='rmse')

100%|██████████| 10/10 [00:00<00:00, 95.82it/s]


Complete similarity analysis step.
Scan step starting ...


In [17]:
result
# EX: For threshold 0.4 RMSE = 5351739296.605793 and Test-samples <= 0.4 similarities = [ 15,  18,  99, 100, 113, 114, 115, 121, 125, 135]

{'Threshold 0.0': [[5240196576.890551], array([], dtype=int64)],
 'Threshold 0.1': [[5258425505.263837], array([125])],
 'Threshold 0.2': [[5258425505.263837], array([125])],
 'Threshold 0.3': [[5259277045.192482], array([ 99, 100, 121, 125])],
 'Threshold 0.4': [[5351739296.605793],
  array([ 15,  18,  99, 100, 113, 114, 115, 121, 125, 135])],
 'Threshold 0.5': [[5317291117.078758],
  array([ 11,  15,  18,  20,  66,  73,  74,  77,  79,  80,  81,  82,  83,
          84,  85,  87,  88,  89,  90,  96,  99, 100, 101, 102, 103, 111,
         112, 113, 114, 115, 121, 125, 135])],
 'Threshold 0.6': [[5785268579.799937],
  array([  4,   8,   9,  10,  11,  14,  15,  18,  19,  20,  37,  38,  53,
          55,  58,  66,  67,  68,  69,  70,  71,  72,  73,  74,  77,  78,
          79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  92,
          93,  95,  96,  99, 100, 101, 102, 103, 106, 107, 110, 111, 112,
         113, 114, 115, 121, 125, 128, 129, 131, 135])],
 'Threshold 0.7': [[55126

In [21]:
# view result as a dataframe
results_df = pd.DataFrame(result).T
results_df.columns = ['RMSE', 'Samples_LT_Threshold']
results_df

RMSE  \
Threshold 0.0  [5240196576.890551]   
Threshold 0.1  [5258425505.263837]   
Threshold 0.2  [5258425505.263837]   
Threshold 0.3  [5259277045.192482]   
Threshold 0.4  [5351739296.605793]   
Threshold 0.5  [5317291117.078758]   
Threshold 0.6  [5785268579.799937]   
Threshold 0.7   [5512687513.14104]   
Threshold 0.8   [5896773530.10294]   
Threshold 0.9  [5329136652.379859]   

                                            Samples_LT_Threshold  
Threshold 0.0                                                 []  
Threshold 0.1                                              [125]  
Threshold 0.2                                              [125]  
Threshold 0.3                                [99, 100, 121, 125]  
Threshold 0.4    [15, 18, 99, 100, 113, 114, 115, 121, 125, 135]  
Threshold 0.5  [11, 15, 18, 20, 66, 73, 74, 77, 79, 80, 81, 8...  
Threshold 0.6  [4, 8, 9, 10, 11, 14, 15, 18, 19, 20, 37, 38, ...  
Threshold 0.7  [0, 2, 3, 4, 7, 8, 9, 10, 11, 14, 15, 17, 18, ...  
Threshold 0.8  [0, 1, 2, 3, 4, 6, 7, 8, 9, 10, 11, 12, 13, 14...  
Threshold 0.9  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...